import React from 'react'

export default function Home() {
  return (
    <div>This is a home page
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde vero nihil expedita ut, saepe, id labore consequatur eos quisquam mollitia impedit, officiis placeat ipsam! Optio aliquid recusandae iste laudantium fugit expedita fuga voluptates doloribus. Ut impedit placeat unde repellat nam repellendus! Vel consectetur unde commodi officia ipsam nisi, quas esse reprehenderit architecto eligendi nulla dicta! Labore expedita ad odit pariatur quae voluptatum voluptate cumque repudiandae? Aliquid eius ipsa reprehenderit deleniti facilis, voluptatum quaerat nemo quasi sed rem quae, cumque debitis eaque illo suscipit laboriosam. Tempore tempora eos excepturi numquam quas sapiente adipisci dolore quo commodi, aperiam soluta repudiandae in, harum nihil nesciunt atque asperiores perspiciatis nemo vitae placeat nam odit quasi! Quaerat vel ducimus praesentium harum dicta sed, suscipit possimus, recusandae ex reiciendis ipsum ipsa incidunt blanditiis eligendi provident tempore adipisci assumenda. Laboriosam eos, odio qui rerum saepe itaque minima molestias iste minus omnis dolorem ipsa corrupti, cumque, non voluptatibus quod fugit? Amet qui voluptates expedita itaque earum deserunt, vero repellendus veritatis illo maxime adipisci harum esse recusandae enim assumenda, quisquam quod magnam nisi similique sunt id, dolores porro quia! Quod, tenetur. Dignissimos, itaque voluptatem quaerat deserunt sed quod. Magnam, aliquid optio! Laboriosam aspernatur recusandae numquam voluptatem nobis! Facilis neque consequatur aspernatur odit dolorum voluptate sed? Itaque doloremque animi rerum impedit voluptatem ad quia esse modi aperiam quod nostrum nemo reprehenderit laudantium quidem eligendi, alias pariatur debitis? At, quos consequuntur eos sint laboriosam debitis quaerat eveniet quia odit vero rerum repellat deserunt praesentium ullam excepturi voluptas consectetur beatae harum. Doloremque debitis sed animi dicta harum adipisci, iste eos eum neque natus ex voluptatum corrupti laudantium soluta culpa veritatis quasi. Provident at excepturi sunt nulla. Veritatis doloribus optio, pariatur tenetur debitis fugit vitae provident ducimus ab sequi magnam fuga culpa sed! Pariatur repellat sed error voluptates, molestias commodi ratione sequi, deserunt itaque laborum eligendi quo, aliquam facilis at qui quasi illo. Labore vel vero nulla. Laboriosam itaque vero nemo id facilis cumque illum voluptatem delectus illo, accusantium temporibus quasi sit quo dignissimos qui ipsa sint animi repellat laudantium debitis? Aut ea excepturi sequi odio voluptate a atque facilis minima harum, nostrum labore laudantium voluptatibus accusamus, delectus ab at. Reprehenderit ducimus consequuntur sed neque veritatis nulla hic corporis quasi molestias soluta ut autem, optio nesciunt at totam, animi accusamus est. Consectetur expedita ipsam eius dolor dolore quasi aliquam aut? Illum numquam, nobis soluta ipsum impedit explicabo perspiciatis in beatae mollitia adipisci quaerat.</p>
    </div>

  )
}
